version: '2'
services:
  redis:
    container_name: redis
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data

  sidekiq:
    container_name: sidekiq
    build: .
    env_file: .env
    command: sh -c "bundle exec thin start -p 8081"
    volumes:
      - .:/sidekiq
    ports:
      - 8081:8081
    links:
      - redis
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local